#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R7.HelpDesk
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="HelpDesk")]
	public partial class HelpDeskDALDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHelpDesk_Log(HelpDesk_Log instance);
    partial void UpdateHelpDesk_Log(HelpDesk_Log instance);
    partial void DeleteHelpDesk_Log(HelpDesk_Log instance);
    partial void InsertHelpDesk_Setting(HelpDesk_Setting instance);
    partial void UpdateHelpDesk_Setting(HelpDesk_Setting instance);
    partial void DeleteHelpDesk_Setting(HelpDesk_Setting instance);
    partial void InsertHelpDesk_TaskAssociation(HelpDesk_TaskAssociation instance);
    partial void UpdateHelpDesk_TaskAssociation(HelpDesk_TaskAssociation instance);
    partial void DeleteHelpDesk_TaskAssociation(HelpDesk_TaskAssociation instance);
    partial void InsertHelpDesk_TaskCategory(HelpDesk_TaskCategory instance);
    partial void UpdateHelpDesk_TaskCategory(HelpDesk_TaskCategory instance);
    partial void DeleteHelpDesk_TaskCategory(HelpDesk_TaskCategory instance);
    partial void InsertHelpDesk_TaskDetail(HelpDesk_TaskDetail instance);
    partial void UpdateHelpDesk_TaskDetail(HelpDesk_TaskDetail instance);
    partial void DeleteHelpDesk_TaskDetail(HelpDesk_TaskDetail instance);
    partial void InsertHelpDesk_Category(HelpDesk_Category instance);
    partial void UpdateHelpDesk_Category(HelpDesk_Category instance);
    partial void DeleteHelpDesk_Category(HelpDesk_Category instance);
    partial void InsertHelpDesk_Attachment(HelpDesk_Attachment instance);
    partial void UpdateHelpDesk_Attachment(HelpDesk_Attachment instance);
    partial void DeleteHelpDesk_Attachment(HelpDesk_Attachment instance);
    partial void InsertHelpDesk_Task(HelpDesk_Task instance);
    partial void UpdateHelpDesk_Task(HelpDesk_Task instance);
    partial void DeleteHelpDesk_Task(HelpDesk_Task instance);
    partial void InsertHelpDesk_Role(HelpDesk_Role instance);
    partial void UpdateHelpDesk_Role(HelpDesk_Role instance);
    partial void DeleteHelpDesk_Role(HelpDesk_Role instance);
    partial void InsertHelpDesk_LastSearch(HelpDesk_LastSearch instance);
    partial void UpdateHelpDesk_LastSearch(HelpDesk_LastSearch instance);
    partial void DeleteHelpDesk_LastSearch(HelpDesk_LastSearch instance);
    #endregion
		
		public HelpDeskDALDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SiteSqlServer"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HelpDeskDALDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HelpDeskDALDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HelpDeskDALDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HelpDeskDALDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HelpDesk_Log> HelpDesk_Logs
		{
			get
			{
				return this.GetTable<HelpDesk_Log>();
			}
		}
		
		public System.Data.Linq.Table<HelpDesk_Setting> HelpDesk_Settings
		{
			get
			{
				return this.GetTable<HelpDesk_Setting>();
			}
		}
		
		public System.Data.Linq.Table<HelpDesk_TaskAssociation> HelpDesk_TaskAssociations
		{
			get
			{
				return this.GetTable<HelpDesk_TaskAssociation>();
			}
		}
		
		public System.Data.Linq.Table<HelpDesk_TaskCategory> HelpDesk_TaskCategories
		{
			get
			{
				return this.GetTable<HelpDesk_TaskCategory>();
			}
		}
		
		public System.Data.Linq.Table<HelpDesk_TaskDetail> HelpDesk_TaskDetails
		{
			get
			{
				return this.GetTable<HelpDesk_TaskDetail>();
			}
		}
		
		public System.Data.Linq.Table<HelpDesk_Category> HelpDesk_Categories
		{
			get
			{
				return this.GetTable<HelpDesk_Category>();
			}
		}
		
		public System.Data.Linq.Table<HelpDesk_Attachment> HelpDesk_Attachments
		{
			get
			{
				return this.GetTable<HelpDesk_Attachment>();
			}
		}
		
		public System.Data.Linq.Table<HelpDesk_Task> HelpDesk_Tasks
		{
			get
			{
				return this.GetTable<HelpDesk_Task>();
			}
		}
		
		public System.Data.Linq.Table<HelpDesk_Role> HelpDesk_Roles
		{
			get
			{
				return this.GetTable<HelpDesk_Role>();
			}
		}
		
		public System.Data.Linq.Table<HelpDesk_LastSearch> HelpDesk_LastSearches
		{
			get
			{
				return this.GetTable<HelpDesk_LastSearch>();
			}
		}
	}
	
	[Table(Name="dbo.HelpDesk_Log")]
	public partial class HelpDesk_Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LogID;
		
		private int _TaskID;
		
		private string _LogDescription;
		
		private System.DateTime _DateCreated;
		
		private int _UserID;
		
		private EntityRef<HelpDesk_Task> _HelpDesk_Task;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLogIDChanging(int value);
    partial void OnLogIDChanged();
    partial void OnTaskIDChanging(int value);
    partial void OnTaskIDChanged();
    partial void OnLogDescriptionChanging(string value);
    partial void OnLogDescriptionChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    #endregion
		
		public HelpDesk_Log()
		{
			this._HelpDesk_Task = default(EntityRef<HelpDesk_Task>);
			OnCreated();
		}
		
		[Column(Storage="_LogID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LogID
		{
			get
			{
				return this._LogID;
			}
			set
			{
				if ((this._LogID != value))
				{
					this.OnLogIDChanging(value);
					this.SendPropertyChanging();
					this._LogID = value;
					this.SendPropertyChanged("LogID");
					this.OnLogIDChanged();
				}
			}
		}
		
		[Column(Storage="_TaskID", DbType="Int NOT NULL")]
		public int TaskID
		{
			get
			{
				return this._TaskID;
			}
			set
			{
				if ((this._TaskID != value))
				{
					if (this._HelpDesk_Task.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTaskIDChanging(value);
					this.SendPropertyChanging();
					this._TaskID = value;
					this.SendPropertyChanged("TaskID");
					this.OnTaskIDChanged();
				}
			}
		}
		
		[Column(Storage="_LogDescription", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string LogDescription
		{
			get
			{
				return this._LogDescription;
			}
			set
			{
				if ((this._LogDescription != value))
				{
					this.OnLogDescriptionChanging(value);
					this.SendPropertyChanging();
					this._LogDescription = value;
					this.SendPropertyChanged("LogDescription");
					this.OnLogDescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[Column(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[Association(Name="HelpDesk_Task_HelpDesk_Log", Storage="_HelpDesk_Task", ThisKey="TaskID", OtherKey="TaskID", IsForeignKey=true)]
		public HelpDesk_Task HelpDesk_Task
		{
			get
			{
				return this._HelpDesk_Task.Entity;
			}
			set
			{
				HelpDesk_Task previousValue = this._HelpDesk_Task.Entity;
				if (((previousValue != value) 
							|| (this._HelpDesk_Task.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HelpDesk_Task.Entity = null;
						previousValue.HelpDesk_Logs.Remove(this);
					}
					this._HelpDesk_Task.Entity = value;
					if ((value != null))
					{
						value.HelpDesk_Logs.Add(this);
						this._TaskID = value.TaskID;
					}
					else
					{
						this._TaskID = default(int);
					}
					this.SendPropertyChanged("HelpDesk_Task");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.HelpDesk_Settings")]
	public partial class HelpDesk_Setting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SettingID;
		
		private int _PortalID;
		
		private string _SettingName;
		
		private string _SettingValue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSettingIDChanging(int value);
    partial void OnSettingIDChanged();
    partial void OnPortalIDChanging(int value);
    partial void OnPortalIDChanged();
    partial void OnSettingNameChanging(string value);
    partial void OnSettingNameChanged();
    partial void OnSettingValueChanging(string value);
    partial void OnSettingValueChanged();
    #endregion
		
		public HelpDesk_Setting()
		{
			OnCreated();
		}
		
		[Column(Storage="_SettingID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SettingID
		{
			get
			{
				return this._SettingID;
			}
			set
			{
				if ((this._SettingID != value))
				{
					this.OnSettingIDChanging(value);
					this.SendPropertyChanging();
					this._SettingID = value;
					this.SendPropertyChanged("SettingID");
					this.OnSettingIDChanged();
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int NOT NULL")]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this.OnPortalIDChanging(value);
					this.SendPropertyChanging();
					this._PortalID = value;
					this.SendPropertyChanged("PortalID");
					this.OnPortalIDChanged();
				}
			}
		}
		
		[Column(Storage="_SettingName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string SettingName
		{
			get
			{
				return this._SettingName;
			}
			set
			{
				if ((this._SettingName != value))
				{
					this.OnSettingNameChanging(value);
					this.SendPropertyChanging();
					this._SettingName = value;
					this.SendPropertyChanged("SettingName");
					this.OnSettingNameChanged();
				}
			}
		}
		
		[Column(Storage="_SettingValue", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string SettingValue
		{
			get
			{
				return this._SettingValue;
			}
			set
			{
				if ((this._SettingValue != value))
				{
					this.OnSettingValueChanging(value);
					this.SendPropertyChanging();
					this._SettingValue = value;
					this.SendPropertyChanged("SettingValue");
					this.OnSettingValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.HelpDesk_TaskAssociations")]
	public partial class HelpDesk_TaskAssociation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TaskRelationID;
		
		private int _TaskID;
		
		private int _AssociatedID;
		
		private EntityRef<HelpDesk_Task> _HelpDesk_Task;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaskRelationIDChanging(int value);
    partial void OnTaskRelationIDChanged();
    partial void OnTaskIDChanging(int value);
    partial void OnTaskIDChanged();
    partial void OnAssociatedIDChanging(int value);
    partial void OnAssociatedIDChanged();
    #endregion
		
		public HelpDesk_TaskAssociation()
		{
			this._HelpDesk_Task = default(EntityRef<HelpDesk_Task>);
			OnCreated();
		}
		
		[Column(Storage="_TaskRelationID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TaskRelationID
		{
			get
			{
				return this._TaskRelationID;
			}
			set
			{
				if ((this._TaskRelationID != value))
				{
					this.OnTaskRelationIDChanging(value);
					this.SendPropertyChanging();
					this._TaskRelationID = value;
					this.SendPropertyChanged("TaskRelationID");
					this.OnTaskRelationIDChanged();
				}
			}
		}
		
		[Column(Storage="_TaskID", DbType="Int NOT NULL")]
		public int TaskID
		{
			get
			{
				return this._TaskID;
			}
			set
			{
				if ((this._TaskID != value))
				{
					if (this._HelpDesk_Task.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTaskIDChanging(value);
					this.SendPropertyChanging();
					this._TaskID = value;
					this.SendPropertyChanged("TaskID");
					this.OnTaskIDChanged();
				}
			}
		}
		
		[Column(Storage="_AssociatedID", DbType="Int NOT NULL")]
		public int AssociatedID
		{
			get
			{
				return this._AssociatedID;
			}
			set
			{
				if ((this._AssociatedID != value))
				{
					this.OnAssociatedIDChanging(value);
					this.SendPropertyChanging();
					this._AssociatedID = value;
					this.SendPropertyChanged("AssociatedID");
					this.OnAssociatedIDChanged();
				}
			}
		}
		
		[Association(Name="HelpDesk_Task_HelpDesk_TaskAssociation", Storage="_HelpDesk_Task", ThisKey="TaskID", OtherKey="TaskID", IsForeignKey=true)]
		public HelpDesk_Task HelpDesk_Task
		{
			get
			{
				return this._HelpDesk_Task.Entity;
			}
			set
			{
				HelpDesk_Task previousValue = this._HelpDesk_Task.Entity;
				if (((previousValue != value) 
							|| (this._HelpDesk_Task.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HelpDesk_Task.Entity = null;
						previousValue.HelpDesk_TaskAssociations.Remove(this);
					}
					this._HelpDesk_Task.Entity = value;
					if ((value != null))
					{
						value.HelpDesk_TaskAssociations.Add(this);
						this._TaskID = value.TaskID;
					}
					else
					{
						this._TaskID = default(int);
					}
					this.SendPropertyChanged("HelpDesk_Task");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.HelpDesk_TaskCategories")]
	public partial class HelpDesk_TaskCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _TaskID;
		
		private int _CategoryID;
		
		private EntityRef<HelpDesk_Category> _HelpDesk_Category;
		
		private EntityRef<HelpDesk_Task> _HelpDesk_Task;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTaskIDChanging(int value);
    partial void OnTaskIDChanged();
    partial void OnCategoryIDChanging(int value);
    partial void OnCategoryIDChanged();
    #endregion
		
		public HelpDesk_TaskCategory()
		{
			this._HelpDesk_Category = default(EntityRef<HelpDesk_Category>);
			this._HelpDesk_Task = default(EntityRef<HelpDesk_Task>);
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_TaskID", DbType="Int NOT NULL")]
		public int TaskID
		{
			get
			{
				return this._TaskID;
			}
			set
			{
				if ((this._TaskID != value))
				{
					if (this._HelpDesk_Task.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTaskIDChanging(value);
					this.SendPropertyChanging();
					this._TaskID = value;
					this.SendPropertyChanged("TaskID");
					this.OnTaskIDChanged();
				}
			}
		}
		
		[Column(Storage="_CategoryID", DbType="Int NOT NULL")]
		public int CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					if (this._HelpDesk_Category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._CategoryID = value;
					this.SendPropertyChanged("CategoryID");
					this.OnCategoryIDChanged();
				}
			}
		}
		
		[Association(Name="HelpDesk_Category_HelpDesk_TaskCategory", Storage="_HelpDesk_Category", ThisKey="CategoryID", OtherKey="CategoryID", IsForeignKey=true)]
		public HelpDesk_Category HelpDesk_Category
		{
			get
			{
				return this._HelpDesk_Category.Entity;
			}
			set
			{
				HelpDesk_Category previousValue = this._HelpDesk_Category.Entity;
				if (((previousValue != value) 
							|| (this._HelpDesk_Category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HelpDesk_Category.Entity = null;
						previousValue.HelpDesk_TaskCategories.Remove(this);
					}
					this._HelpDesk_Category.Entity = value;
					if ((value != null))
					{
						value.HelpDesk_TaskCategories.Add(this);
						this._CategoryID = value.CategoryID;
					}
					else
					{
						this._CategoryID = default(int);
					}
					this.SendPropertyChanged("HelpDesk_Category");
				}
			}
		}
		
		[Association(Name="HelpDesk_Task_HelpDesk_TaskCategory", Storage="_HelpDesk_Task", ThisKey="TaskID", OtherKey="TaskID", IsForeignKey=true)]
		public HelpDesk_Task HelpDesk_Task
		{
			get
			{
				return this._HelpDesk_Task.Entity;
			}
			set
			{
				HelpDesk_Task previousValue = this._HelpDesk_Task.Entity;
				if (((previousValue != value) 
							|| (this._HelpDesk_Task.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HelpDesk_Task.Entity = null;
						previousValue.HelpDesk_TaskCategories.Remove(this);
					}
					this._HelpDesk_Task.Entity = value;
					if ((value != null))
					{
						value.HelpDesk_TaskCategories.Add(this);
						this._TaskID = value.TaskID;
					}
					else
					{
						this._TaskID = default(int);
					}
					this.SendPropertyChanged("HelpDesk_Task");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.HelpDesk_TaskDetails")]
	public partial class HelpDesk_TaskDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DetailID;
		
		private int _TaskID;
		
		private string _DetailType;
		
		private System.DateTime _InsertDate;
		
		private int _UserID;
		
		private string _Description;
		
		private System.Nullable<System.DateTime> _StartTime;
		
		private System.Nullable<System.DateTime> _StopTime;
		
		private EntitySet<HelpDesk_Attachment> _HelpDesk_Attachments;
		
		private EntityRef<HelpDesk_Task> _HelpDesk_Task;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDetailIDChanging(int value);
    partial void OnDetailIDChanged();
    partial void OnTaskIDChanging(int value);
    partial void OnTaskIDChanged();
    partial void OnDetailTypeChanging(string value);
    partial void OnDetailTypeChanged();
    partial void OnInsertDateChanging(System.DateTime value);
    partial void OnInsertDateChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnStartTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnStartTimeChanged();
    partial void OnStopTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnStopTimeChanged();
    #endregion
		
		public HelpDesk_TaskDetail()
		{
			this._HelpDesk_Attachments = new EntitySet<HelpDesk_Attachment>(new Action<HelpDesk_Attachment>(this.attach_HelpDesk_Attachments), new Action<HelpDesk_Attachment>(this.detach_HelpDesk_Attachments));
			this._HelpDesk_Task = default(EntityRef<HelpDesk_Task>);
			OnCreated();
		}
		
		[Column(Storage="_DetailID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DetailID
		{
			get
			{
				return this._DetailID;
			}
			set
			{
				if ((this._DetailID != value))
				{
					this.OnDetailIDChanging(value);
					this.SendPropertyChanging();
					this._DetailID = value;
					this.SendPropertyChanged("DetailID");
					this.OnDetailIDChanged();
				}
			}
		}
		
		[Column(Storage="_TaskID", DbType="Int NOT NULL")]
		public int TaskID
		{
			get
			{
				return this._TaskID;
			}
			set
			{
				if ((this._TaskID != value))
				{
					if (this._HelpDesk_Task.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTaskIDChanging(value);
					this.SendPropertyChanging();
					this._TaskID = value;
					this.SendPropertyChanged("TaskID");
					this.OnTaskIDChanged();
				}
			}
		}
		
		[Column(Storage="_DetailType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DetailType
		{
			get
			{
				return this._DetailType;
			}
			set
			{
				if ((this._DetailType != value))
				{
					this.OnDetailTypeChanging(value);
					this.SendPropertyChanging();
					this._DetailType = value;
					this.SendPropertyChanged("DetailType");
					this.OnDetailTypeChanged();
				}
			}
		}
		
		[Column(Storage="_InsertDate", DbType="DateTime NOT NULL")]
		public System.DateTime InsertDate
		{
			get
			{
				return this._InsertDate;
			}
			set
			{
				if ((this._InsertDate != value))
				{
					this.OnInsertDateChanging(value);
					this.SendPropertyChanging();
					this._InsertDate = value;
					this.SendPropertyChanged("InsertDate");
					this.OnInsertDateChanged();
				}
			}
		}
		
		[Column(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_StartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartTime
		{
			get
			{
				return this._StartTime;
			}
			set
			{
				if ((this._StartTime != value))
				{
					this.OnStartTimeChanging(value);
					this.SendPropertyChanging();
					this._StartTime = value;
					this.SendPropertyChanged("StartTime");
					this.OnStartTimeChanged();
				}
			}
		}
		
		[Column(Storage="_StopTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> StopTime
		{
			get
			{
				return this._StopTime;
			}
			set
			{
				if ((this._StopTime != value))
				{
					this.OnStopTimeChanging(value);
					this.SendPropertyChanging();
					this._StopTime = value;
					this.SendPropertyChanged("StopTime");
					this.OnStopTimeChanged();
				}
			}
		}
		
		[Association(Name="HelpDesk_TaskDetail_HelpDesk_Attachment", Storage="_HelpDesk_Attachments", ThisKey="DetailID", OtherKey="DetailID")]
		public EntitySet<HelpDesk_Attachment> HelpDesk_Attachments
		{
			get
			{
				return this._HelpDesk_Attachments;
			}
			set
			{
				this._HelpDesk_Attachments.Assign(value);
			}
		}
		
		[Association(Name="HelpDesk_Task_HelpDesk_TaskDetail", Storage="_HelpDesk_Task", ThisKey="TaskID", OtherKey="TaskID", IsForeignKey=true)]
		public HelpDesk_Task HelpDesk_Task
		{
			get
			{
				return this._HelpDesk_Task.Entity;
			}
			set
			{
				HelpDesk_Task previousValue = this._HelpDesk_Task.Entity;
				if (((previousValue != value) 
							|| (this._HelpDesk_Task.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HelpDesk_Task.Entity = null;
						previousValue.HelpDesk_TaskDetails.Remove(this);
					}
					this._HelpDesk_Task.Entity = value;
					if ((value != null))
					{
						value.HelpDesk_TaskDetails.Add(this);
						this._TaskID = value.TaskID;
					}
					else
					{
						this._TaskID = default(int);
					}
					this.SendPropertyChanged("HelpDesk_Task");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HelpDesk_Attachments(HelpDesk_Attachment entity)
		{
			this.SendPropertyChanging();
			entity.HelpDesk_TaskDetail = this;
		}
		
		private void detach_HelpDesk_Attachments(HelpDesk_Attachment entity)
		{
			this.SendPropertyChanging();
			entity.HelpDesk_TaskDetail = null;
		}
	}
	
	[Table(Name="dbo.HelpDesk_Categories")]
	public partial class HelpDesk_Category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CategoryID;
		
		private int _PortalID;
		
		private System.Nullable<int> _ParentCategoryID;
		
		private string _CategoryName;
		
		private System.Nullable<int> _Level;
		
		private bool _RequestorVisible;
		
		private bool _Selectable;
		
		private EntitySet<HelpDesk_TaskCategory> _HelpDesk_TaskCategories;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategoryIDChanging(int value);
    partial void OnCategoryIDChanged();
    partial void OnPortalIDChanging(int value);
    partial void OnPortalIDChanged();
    partial void OnParentCategoryIDChanging(System.Nullable<int> value);
    partial void OnParentCategoryIDChanged();
    partial void OnCategoryNameChanging(string value);
    partial void OnCategoryNameChanged();
    partial void OnLevelChanging(System.Nullable<int> value);
    partial void OnLevelChanged();
    partial void OnRequestorVisibleChanging(bool value);
    partial void OnRequestorVisibleChanged();
    partial void OnSelectableChanging(bool value);
    partial void OnSelectableChanged();
    #endregion
		
		public HelpDesk_Category()
		{
			this._HelpDesk_TaskCategories = new EntitySet<HelpDesk_TaskCategory>(new Action<HelpDesk_TaskCategory>(this.attach_HelpDesk_TaskCategories), new Action<HelpDesk_TaskCategory>(this.detach_HelpDesk_TaskCategories));
			OnCreated();
		}
		
		[Column(Storage="_CategoryID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					this.OnCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._CategoryID = value;
					this.SendPropertyChanged("CategoryID");
					this.OnCategoryIDChanged();
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int NOT NULL")]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this.OnPortalIDChanging(value);
					this.SendPropertyChanging();
					this._PortalID = value;
					this.SendPropertyChanged("PortalID");
					this.OnPortalIDChanged();
				}
			}
		}
		
		[Column(Storage="_ParentCategoryID", DbType="Int")]
		public System.Nullable<int> ParentCategoryID
		{
			get
			{
				return this._ParentCategoryID;
			}
			set
			{
				if ((this._ParentCategoryID != value))
				{
					this.OnParentCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._ParentCategoryID = value;
					this.SendPropertyChanged("ParentCategoryID");
					this.OnParentCategoryIDChanged();
				}
			}
		}
		
		[Column(Storage="_CategoryName", DbType="NVarChar(50)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this.OnCategoryNameChanging(value);
					this.SendPropertyChanging();
					this._CategoryName = value;
					this.SendPropertyChanged("CategoryName");
					this.OnCategoryNameChanged();
				}
			}
		}
		
		[Column(Name="[Level]", Storage="_Level", DbType="Int")]
		public System.Nullable<int> Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this.OnLevelChanging(value);
					this.SendPropertyChanging();
					this._Level = value;
					this.SendPropertyChanged("Level");
					this.OnLevelChanged();
				}
			}
		}
		
		[Column(Storage="_RequestorVisible", DbType="Bit NOT NULL")]
		public bool RequestorVisible
		{
			get
			{
				return this._RequestorVisible;
			}
			set
			{
				if ((this._RequestorVisible != value))
				{
					this.OnRequestorVisibleChanging(value);
					this.SendPropertyChanging();
					this._RequestorVisible = value;
					this.SendPropertyChanged("RequestorVisible");
					this.OnRequestorVisibleChanged();
				}
			}
		}
		
		[Column(Storage="_Selectable", DbType="Bit NOT NULL")]
		public bool Selectable
		{
			get
			{
				return this._Selectable;
			}
			set
			{
				if ((this._Selectable != value))
				{
					this.OnSelectableChanging(value);
					this.SendPropertyChanging();
					this._Selectable = value;
					this.SendPropertyChanged("Selectable");
					this.OnSelectableChanged();
				}
			}
		}
		
		[Association(Name="HelpDesk_Category_HelpDesk_TaskCategory", Storage="_HelpDesk_TaskCategories", ThisKey="CategoryID", OtherKey="CategoryID")]
		public EntitySet<HelpDesk_TaskCategory> HelpDesk_TaskCategories
		{
			get
			{
				return this._HelpDesk_TaskCategories;
			}
			set
			{
				this._HelpDesk_TaskCategories.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HelpDesk_TaskCategories(HelpDesk_TaskCategory entity)
		{
			this.SendPropertyChanging();
			entity.HelpDesk_Category = this;
		}
		
		private void detach_HelpDesk_TaskCategories(HelpDesk_TaskCategory entity)
		{
			this.SendPropertyChanging();
			entity.HelpDesk_Category = null;
		}
	}
	
	[Table(Name="dbo.HelpDesk_Attachments")]
	public partial class HelpDesk_Attachment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AttachmentID;
		
		private int _DetailID;
		
		private string _AttachmentPath;
		
		private string _FileName;
		
		private string _OriginalFileName;
		
		private int _UserID;
		
		private EntityRef<HelpDesk_TaskDetail> _HelpDesk_TaskDetail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAttachmentIDChanging(int value);
    partial void OnAttachmentIDChanged();
    partial void OnDetailIDChanging(int value);
    partial void OnDetailIDChanged();
    partial void OnAttachmentPathChanging(string value);
    partial void OnAttachmentPathChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnOriginalFileNameChanging(string value);
    partial void OnOriginalFileNameChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    #endregion
		
		public HelpDesk_Attachment()
		{
			this._HelpDesk_TaskDetail = default(EntityRef<HelpDesk_TaskDetail>);
			OnCreated();
		}
		
		[Column(Storage="_AttachmentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AttachmentID
		{
			get
			{
				return this._AttachmentID;
			}
			set
			{
				if ((this._AttachmentID != value))
				{
					this.OnAttachmentIDChanging(value);
					this.SendPropertyChanging();
					this._AttachmentID = value;
					this.SendPropertyChanged("AttachmentID");
					this.OnAttachmentIDChanged();
				}
			}
		}
		
		[Column(Storage="_DetailID", DbType="Int NOT NULL")]
		public int DetailID
		{
			get
			{
				return this._DetailID;
			}
			set
			{
				if ((this._DetailID != value))
				{
					if (this._HelpDesk_TaskDetail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDetailIDChanging(value);
					this.SendPropertyChanging();
					this._DetailID = value;
					this.SendPropertyChanged("DetailID");
					this.OnDetailIDChanged();
				}
			}
		}
		
		[Column(Storage="_AttachmentPath", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string AttachmentPath
		{
			get
			{
				return this._AttachmentPath;
			}
			set
			{
				if ((this._AttachmentPath != value))
				{
					this.OnAttachmentPathChanging(value);
					this.SendPropertyChanging();
					this._AttachmentPath = value;
					this.SendPropertyChanged("AttachmentPath");
					this.OnAttachmentPathChanged();
				}
			}
		}
		
		[Column(Storage="_FileName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[Column(Storage="_OriginalFileName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string OriginalFileName
		{
			get
			{
				return this._OriginalFileName;
			}
			set
			{
				if ((this._OriginalFileName != value))
				{
					this.OnOriginalFileNameChanging(value);
					this.SendPropertyChanging();
					this._OriginalFileName = value;
					this.SendPropertyChanged("OriginalFileName");
					this.OnOriginalFileNameChanged();
				}
			}
		}
		
		[Column(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[Association(Name="HelpDesk_TaskDetail_HelpDesk_Attachment", Storage="_HelpDesk_TaskDetail", ThisKey="DetailID", OtherKey="DetailID", IsForeignKey=true)]
		public HelpDesk_TaskDetail HelpDesk_TaskDetail
		{
			get
			{
				return this._HelpDesk_TaskDetail.Entity;
			}
			set
			{
				HelpDesk_TaskDetail previousValue = this._HelpDesk_TaskDetail.Entity;
				if (((previousValue != value) 
							|| (this._HelpDesk_TaskDetail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HelpDesk_TaskDetail.Entity = null;
						previousValue.HelpDesk_Attachments.Remove(this);
					}
					this._HelpDesk_TaskDetail.Entity = value;
					if ((value != null))
					{
						value.HelpDesk_Attachments.Add(this);
						this._DetailID = value.DetailID;
					}
					else
					{
						this._DetailID = default(int);
					}
					this.SendPropertyChanged("HelpDesk_TaskDetail");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.HelpDesk_Tasks")]
	public partial class HelpDesk_Task : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TaskID;
		
		private int _PortalID;
		
		private string _Description;
		
		private string _Status;
		
		private string _Priority;
		
		private System.DateTime _CreatedDate;
		
		private System.Nullable<System.DateTime> _EstimatedStart;
		
		private System.Nullable<System.DateTime> _EstimatedCompletion;
		
		private System.Nullable<System.DateTime> _DueDate;
		
		private int _AssignedRoleID;
		
		private string _TicketPassword;
		
		private int _RequesterUserID;
		
		private string _RequesterName;
		
		private string _RequesterEmail;
		
		private string _RequesterPhone;
		
		private System.Nullable<int> _EstimatedHours;
		
		private EntitySet<HelpDesk_Log> _HelpDesk_Logs;
		
		private EntitySet<HelpDesk_TaskAssociation> _HelpDesk_TaskAssociations;
		
		private EntitySet<HelpDesk_TaskCategory> _HelpDesk_TaskCategories;
		
		private EntitySet<HelpDesk_TaskDetail> _HelpDesk_TaskDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaskIDChanging(int value);
    partial void OnTaskIDChanged();
    partial void OnPortalIDChanging(int value);
    partial void OnPortalIDChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnPriorityChanging(string value);
    partial void OnPriorityChanged();
    partial void OnCreatedDateChanging(System.DateTime value);
    partial void OnCreatedDateChanged();
    partial void OnEstimatedStartChanging(System.Nullable<System.DateTime> value);
    partial void OnEstimatedStartChanged();
    partial void OnEstimatedCompletionChanging(System.Nullable<System.DateTime> value);
    partial void OnEstimatedCompletionChanged();
    partial void OnDueDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDueDateChanged();
    partial void OnAssignedRoleIDChanging(int value);
    partial void OnAssignedRoleIDChanged();
    partial void OnTicketPasswordChanging(string value);
    partial void OnTicketPasswordChanged();
    partial void OnRequesterUserIDChanging(int value);
    partial void OnRequesterUserIDChanged();
    partial void OnRequesterNameChanging(string value);
    partial void OnRequesterNameChanged();
    partial void OnRequesterEmailChanging(string value);
    partial void OnRequesterEmailChanged();
    partial void OnRequesterPhoneChanging(string value);
    partial void OnRequesterPhoneChanged();
    partial void OnEstimatedHoursChanging(System.Nullable<int> value);
    partial void OnEstimatedHoursChanged();
    #endregion
		
		public HelpDesk_Task()
		{
			this._HelpDesk_Logs = new EntitySet<HelpDesk_Log>(new Action<HelpDesk_Log>(this.attach_HelpDesk_Logs), new Action<HelpDesk_Log>(this.detach_HelpDesk_Logs));
			this._HelpDesk_TaskAssociations = new EntitySet<HelpDesk_TaskAssociation>(new Action<HelpDesk_TaskAssociation>(this.attach_HelpDesk_TaskAssociations), new Action<HelpDesk_TaskAssociation>(this.detach_HelpDesk_TaskAssociations));
			this._HelpDesk_TaskCategories = new EntitySet<HelpDesk_TaskCategory>(new Action<HelpDesk_TaskCategory>(this.attach_HelpDesk_TaskCategories), new Action<HelpDesk_TaskCategory>(this.detach_HelpDesk_TaskCategories));
			this._HelpDesk_TaskDetails = new EntitySet<HelpDesk_TaskDetail>(new Action<HelpDesk_TaskDetail>(this.attach_HelpDesk_TaskDetails), new Action<HelpDesk_TaskDetail>(this.detach_HelpDesk_TaskDetails));
			OnCreated();
		}
		
		[Column(Storage="_TaskID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TaskID
		{
			get
			{
				return this._TaskID;
			}
			set
			{
				if ((this._TaskID != value))
				{
					this.OnTaskIDChanging(value);
					this.SendPropertyChanging();
					this._TaskID = value;
					this.SendPropertyChanged("TaskID");
					this.OnTaskIDChanged();
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int NOT NULL")]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this.OnPortalIDChanging(value);
					this.SendPropertyChanging();
					this._PortalID = value;
					this.SendPropertyChanged("PortalID");
					this.OnPortalIDChanged();
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_Status", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[Column(Storage="_Priority", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[Column(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[Column(Storage="_EstimatedStart", DbType="DateTime")]
		public System.Nullable<System.DateTime> EstimatedStart
		{
			get
			{
				return this._EstimatedStart;
			}
			set
			{
				if ((this._EstimatedStart != value))
				{
					this.OnEstimatedStartChanging(value);
					this.SendPropertyChanging();
					this._EstimatedStart = value;
					this.SendPropertyChanged("EstimatedStart");
					this.OnEstimatedStartChanged();
				}
			}
		}
		
		[Column(Storage="_EstimatedCompletion", DbType="DateTime")]
		public System.Nullable<System.DateTime> EstimatedCompletion
		{
			get
			{
				return this._EstimatedCompletion;
			}
			set
			{
				if ((this._EstimatedCompletion != value))
				{
					this.OnEstimatedCompletionChanging(value);
					this.SendPropertyChanging();
					this._EstimatedCompletion = value;
					this.SendPropertyChanged("EstimatedCompletion");
					this.OnEstimatedCompletionChanged();
				}
			}
		}
		
		[Column(Storage="_DueDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DueDate
		{
			get
			{
				return this._DueDate;
			}
			set
			{
				if ((this._DueDate != value))
				{
					this.OnDueDateChanging(value);
					this.SendPropertyChanging();
					this._DueDate = value;
					this.SendPropertyChanged("DueDate");
					this.OnDueDateChanged();
				}
			}
		}
		
		[Column(Storage="_AssignedRoleID", DbType="Int NOT NULL")]
		public int AssignedRoleID
		{
			get
			{
				return this._AssignedRoleID;
			}
			set
			{
				if ((this._AssignedRoleID != value))
				{
					this.OnAssignedRoleIDChanging(value);
					this.SendPropertyChanging();
					this._AssignedRoleID = value;
					this.SendPropertyChanged("AssignedRoleID");
					this.OnAssignedRoleIDChanged();
				}
			}
		}
		
		[Column(Storage="_TicketPassword", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TicketPassword
		{
			get
			{
				return this._TicketPassword;
			}
			set
			{
				if ((this._TicketPassword != value))
				{
					this.OnTicketPasswordChanging(value);
					this.SendPropertyChanging();
					this._TicketPassword = value;
					this.SendPropertyChanged("TicketPassword");
					this.OnTicketPasswordChanged();
				}
			}
		}
		
		[Column(Storage="_RequesterUserID", DbType="Int NOT NULL")]
		public int RequesterUserID
		{
			get
			{
				return this._RequesterUserID;
			}
			set
			{
				if ((this._RequesterUserID != value))
				{
					this.OnRequesterUserIDChanging(value);
					this.SendPropertyChanging();
					this._RequesterUserID = value;
					this.SendPropertyChanged("RequesterUserID");
					this.OnRequesterUserIDChanged();
				}
			}
		}
		
		[Column(Storage="_RequesterName", DbType="NVarChar(350)")]
		public string RequesterName
		{
			get
			{
				return this._RequesterName;
			}
			set
			{
				if ((this._RequesterName != value))
				{
					this.OnRequesterNameChanging(value);
					this.SendPropertyChanging();
					this._RequesterName = value;
					this.SendPropertyChanged("RequesterName");
					this.OnRequesterNameChanged();
				}
			}
		}
		
		[Column(Storage="_RequesterEmail", DbType="NVarChar(350)")]
		public string RequesterEmail
		{
			get
			{
				return this._RequesterEmail;
			}
			set
			{
				if ((this._RequesterEmail != value))
				{
					this.OnRequesterEmailChanging(value);
					this.SendPropertyChanging();
					this._RequesterEmail = value;
					this.SendPropertyChanged("RequesterEmail");
					this.OnRequesterEmailChanged();
				}
			}
		}
		
		[Column(Storage="_RequesterPhone", DbType="NVarChar(50)")]
		public string RequesterPhone
		{
			get
			{
				return this._RequesterPhone;
			}
			set
			{
				if ((this._RequesterPhone != value))
				{
					this.OnRequesterPhoneChanging(value);
					this.SendPropertyChanging();
					this._RequesterPhone = value;
					this.SendPropertyChanged("RequesterPhone");
					this.OnRequesterPhoneChanged();
				}
			}
		}
		
		[Column(Storage="_EstimatedHours", DbType="Int")]
		public System.Nullable<int> EstimatedHours
		{
			get
			{
				return this._EstimatedHours;
			}
			set
			{
				if ((this._EstimatedHours != value))
				{
					this.OnEstimatedHoursChanging(value);
					this.SendPropertyChanging();
					this._EstimatedHours = value;
					this.SendPropertyChanged("EstimatedHours");
					this.OnEstimatedHoursChanged();
				}
			}
		}
		
		[Association(Name="HelpDesk_Task_HelpDesk_Log", Storage="_HelpDesk_Logs", ThisKey="TaskID", OtherKey="TaskID")]
		public EntitySet<HelpDesk_Log> HelpDesk_Logs
		{
			get
			{
				return this._HelpDesk_Logs;
			}
			set
			{
				this._HelpDesk_Logs.Assign(value);
			}
		}
		
		[Association(Name="HelpDesk_Task_HelpDesk_TaskAssociation", Storage="_HelpDesk_TaskAssociations", ThisKey="TaskID", OtherKey="TaskID")]
		public EntitySet<HelpDesk_TaskAssociation> HelpDesk_TaskAssociations
		{
			get
			{
				return this._HelpDesk_TaskAssociations;
			}
			set
			{
				this._HelpDesk_TaskAssociations.Assign(value);
			}
		}
		
		[Association(Name="HelpDesk_Task_HelpDesk_TaskCategory", Storage="_HelpDesk_TaskCategories", ThisKey="TaskID", OtherKey="TaskID")]
		public EntitySet<HelpDesk_TaskCategory> HelpDesk_TaskCategories
		{
			get
			{
				return this._HelpDesk_TaskCategories;
			}
			set
			{
				this._HelpDesk_TaskCategories.Assign(value);
			}
		}
		
		[Association(Name="HelpDesk_Task_HelpDesk_TaskDetail", Storage="_HelpDesk_TaskDetails", ThisKey="TaskID", OtherKey="TaskID")]
		public EntitySet<HelpDesk_TaskDetail> HelpDesk_TaskDetails
		{
			get
			{
				return this._HelpDesk_TaskDetails;
			}
			set
			{
				this._HelpDesk_TaskDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HelpDesk_Logs(HelpDesk_Log entity)
		{
			this.SendPropertyChanging();
			entity.HelpDesk_Task = this;
		}
		
		private void detach_HelpDesk_Logs(HelpDesk_Log entity)
		{
			this.SendPropertyChanging();
			entity.HelpDesk_Task = null;
		}
		
		private void attach_HelpDesk_TaskAssociations(HelpDesk_TaskAssociation entity)
		{
			this.SendPropertyChanging();
			entity.HelpDesk_Task = this;
		}
		
		private void detach_HelpDesk_TaskAssociations(HelpDesk_TaskAssociation entity)
		{
			this.SendPropertyChanging();
			entity.HelpDesk_Task = null;
		}
		
		private void attach_HelpDesk_TaskCategories(HelpDesk_TaskCategory entity)
		{
			this.SendPropertyChanging();
			entity.HelpDesk_Task = this;
		}
		
		private void detach_HelpDesk_TaskCategories(HelpDesk_TaskCategory entity)
		{
			this.SendPropertyChanging();
			entity.HelpDesk_Task = null;
		}
		
		private void attach_HelpDesk_TaskDetails(HelpDesk_TaskDetail entity)
		{
			this.SendPropertyChanging();
			entity.HelpDesk_Task = this;
		}
		
		private void detach_HelpDesk_TaskDetails(HelpDesk_TaskDetail entity)
		{
			this.SendPropertyChanging();
			entity.HelpDesk_Task = null;
		}
	}
	
	[Table(Name="dbo.HelpDesk_Roles")]
	public partial class HelpDesk_Role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _PortalID;
		
		private int _RoleID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPortalIDChanging(int value);
    partial void OnPortalIDChanged();
    partial void OnRoleIDChanging(int value);
    partial void OnRoleIDChanged();
    #endregion
		
		public HelpDesk_Role()
		{
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int NOT NULL")]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this.OnPortalIDChanging(value);
					this.SendPropertyChanging();
					this._PortalID = value;
					this.SendPropertyChanged("PortalID");
					this.OnPortalIDChanged();
				}
			}
		}
		
		[Column(Storage="_RoleID", DbType="Int NOT NULL")]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.HelpDesk_LastSearch")]
	public partial class HelpDesk_LastSearch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _UserID;
		
		private int _PortalID;
		
		private string _SearchText;
		
		private string _Status;
		
		private string _Priority;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<System.DateTime> _DueDate;
		
		private System.Nullable<int> _AssignedRoleID;
		
		private string _Categories;
		
		private System.Nullable<int> _CurrentPage;
		
		private System.Nullable<int> _PageSize;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnPortalIDChanging(int value);
    partial void OnPortalIDChanged();
    partial void OnSearchTextChanging(string value);
    partial void OnSearchTextChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnPriorityChanging(string value);
    partial void OnPriorityChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnDueDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDueDateChanged();
    partial void OnAssignedRoleIDChanging(System.Nullable<int> value);
    partial void OnAssignedRoleIDChanged();
    partial void OnCategoriesChanging(string value);
    partial void OnCategoriesChanged();
    partial void OnCurrentPageChanging(System.Nullable<int> value);
    partial void OnCurrentPageChanged();
    partial void OnPageSizeChanging(System.Nullable<int> value);
    partial void OnPageSizeChanged();
    #endregion
		
		public HelpDesk_LastSearch()
		{
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int NOT NULL")]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this.OnPortalIDChanging(value);
					this.SendPropertyChanging();
					this._PortalID = value;
					this.SendPropertyChanged("PortalID");
					this.OnPortalIDChanged();
				}
			}
		}
		
		[Column(Storage="_SearchText", DbType="NVarChar(150)")]
		public string SearchText
		{
			get
			{
				return this._SearchText;
			}
			set
			{
				if ((this._SearchText != value))
				{
					this.OnSearchTextChanging(value);
					this.SendPropertyChanging();
					this._SearchText = value;
					this.SendPropertyChanged("SearchText");
					this.OnSearchTextChanged();
				}
			}
		}
		
		[Column(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[Column(Storage="_Priority", DbType="NVarChar(50)")]
		public string Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[Column(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[Column(Storage="_DueDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DueDate
		{
			get
			{
				return this._DueDate;
			}
			set
			{
				if ((this._DueDate != value))
				{
					this.OnDueDateChanging(value);
					this.SendPropertyChanging();
					this._DueDate = value;
					this.SendPropertyChanged("DueDate");
					this.OnDueDateChanged();
				}
			}
		}
		
		[Column(Storage="_AssignedRoleID", DbType="Int")]
		public System.Nullable<int> AssignedRoleID
		{
			get
			{
				return this._AssignedRoleID;
			}
			set
			{
				if ((this._AssignedRoleID != value))
				{
					this.OnAssignedRoleIDChanging(value);
					this.SendPropertyChanging();
					this._AssignedRoleID = value;
					this.SendPropertyChanged("AssignedRoleID");
					this.OnAssignedRoleIDChanged();
				}
			}
		}
		
		[Column(Storage="_Categories", DbType="NVarChar(2000)")]
		public string Categories
		{
			get
			{
				return this._Categories;
			}
			set
			{
				if ((this._Categories != value))
				{
					this.OnCategoriesChanging(value);
					this.SendPropertyChanging();
					this._Categories = value;
					this.SendPropertyChanged("Categories");
					this.OnCategoriesChanged();
				}
			}
		}
		
		[Column(Storage="_CurrentPage", DbType="Int")]
		public System.Nullable<int> CurrentPage
		{
			get
			{
				return this._CurrentPage;
			}
			set
			{
				if ((this._CurrentPage != value))
				{
					this.OnCurrentPageChanging(value);
					this.SendPropertyChanging();
					this._CurrentPage = value;
					this.SendPropertyChanged("CurrentPage");
					this.OnCurrentPageChanged();
				}
			}
		}
		
		[Column(Storage="_PageSize", DbType="Int")]
		public System.Nullable<int> PageSize
		{
			get
			{
				return this._PageSize;
			}
			set
			{
				if ((this._PageSize != value))
				{
					this.OnPageSizeChanging(value);
					this.SendPropertyChanging();
					this._PageSize = value;
					this.SendPropertyChanged("PageSize");
					this.OnPageSizeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
